module.exports =

{
    "en": {
        "helpTitle": "Help with Ougi",
        "helpDesc": "Here's some information about what Ougi can do.",
        "helpPrefix": "Ougi's prefix",
        "helpPrefixExplanation": "This is what you should start your message with if you want Ougi to perform any of the following commands.",
        "helpHelpCommand": "Help command",
        "helpHelpExplanation": "Shows this help menu. You may also use this command plus the name of another command to show detailed information about it.",
        "example": "Example",
        "output": "Output",
        "availableCommands": "Available commands",
        "availableCommandsList": "As of now, Ougi has these commands",
        "improving": "Still improving!",
        "mustGuild": "You must be in a server to run this command.",
        "mustOwn": "You must be the server's owner to run this command.",
        "oneCharWhitelist": "Ara ara, provide a phrase or a command that is at least one character long in order to whitelist it.",
        "massivePing": "Ora ora ora ora! Remove that massive ping.",
        "avoidSpecialChar": "Avoid mentions or custom emoji please. What? Isn't that a mention or a custom emoji? Well, then don't include '<@' and '>' in the same message.",
        "reactingTo": "I'll start reacting to {triggerName} in {guildName}.",
        "alrightWhitelisted": "Alright, I've whitelisted {triggerName} in {guildName}.",
        "notBlacklisted": "Looks like this trigger wasn't blacklisted at all.",
        "validLang": "Please select a valid language. Refer to the following command if you are clueless.",
        "specificHelpTitle": "Ougi's {commandName} command",
        "onlyGuilds": "This is only available in Discord servers.",
        "inGuildWarning": "You must be in a Discord server in order to preview information about this command.",
        "keywordRequired": "Please provide at least one keyword to search.",
        "allowUsage": "Use this command to whitelist a trigger that is currently blacklisted in this Discord server, Ougi will start processing that input.",
        "specialPermission": "Special permission required",
        "onlyOwner": "You must be the owner of whatever Discord server you run this command in.",
        "possibleDelay": "Execution delay",
        "delayWarning": "Some languages aren't fully implemented so certain commands might take a few extra seconds to translate and execute.",
        "newLang": "Language set to {langName}.",
        "langDesc": "Ougi will use this language when talking to you.",
        "newLangGuild": "Guild language set to {langName}.",
        "langGuildDesc": "Ougi will use this language inside {guildName}.",
        "yes": "Yes",
        "no": "No",
        "yeah": "Yeah",
        "nah": "Nah",
        "maybe": "Maybe",
        "maybeNot": "Maybe not.",
        "guess": "I guess.",
        "guessNot": "I guess not.",
        "idk": "I don't really know so I can't actually answer.",
        "notSure": "I'm not sure.",
        "askSomeone": "Ask someone else.",
        "negative": "Negative",
        "squareNegative": "Negative multiplied by negative.",
        "pancakes": "Pancakes",
        "impossible": "**Impossible**",
        "notWhoKnows": "I don't know the answer, but you do.",
        "skipQuestion": "Do you really want me to answer that?",
        "uh": "Uh...",
        "questionA": "Do you like tacos?",
        "questionB": "Are you human?",
        "questionC": "Are you ever gonna give me up?",
        "answerHelpDesc": "Ask Ougi a yes-or-no question.",
        "seeEmoji": "I couldn't find one or more of the emoji you asked me for. Execute the following command to see my emoji list",
        "pleaseIncludeEmoji": "Please provide at least one emoji name. Execute the following command to see my emoji list",
        "commandOption": "Previewing information about the {optionName} option. Remember these command options should be written after {commandName} in order to use them.",
        "embedAuthor": "An embed's author name, which appears in the top. It can be plain text or an user mention.",
        "embedAuthorURL": "An URL to mask within an embed's author name, so it'll work like a link when an user clicks over it.",
        "embedAvatar": "Image to use as author avatar.",
        "embedTitle": "Text to use as an embed's title.",
        "embedTitleURL": "An URL to mask within an embed's title, so it'll work like a link when an user clicks over it.",
        "embedDescription": "Text for the description of an embed.",
        "embedSubtitle": "Text to use as subtitle for an embed, also known as a field's title. You can add up to 25 subtitles. The order for these depends in which order you add them.",
        "embedField": "Text to use as field for an embed, below each subtitle. You can add up to 25 fields. The order for these depends in which order you add them.",
        "embedColor": "Color for an embed. It can be an hexadecimal value, RGB value or a supported color name.",
        "embedThumbnail": "Image to use as thumbnail.",
        "embedImage": "Image to display widely across an embed.",
        "embedFooter": "Text for the bottom of an embed.",
        "embedIcon": "Small icon to include in the bottom left corner.",
        "embedTimestamp": "If included, a timestamp will be added to the footer.",
        "embedSave": "This option allows you to save your embed as a named preset (only available to yourself!).",
        "embedLoad": "This option allows you to load a previously saved preset and apply it to your new embed. You may also use it to merge presets or modify them with another command option.",
        "embedShare": "This option allows you to share your preset with an user.",
        "embedDelete": "This option allows you to delete a previously saved preset.",
        "embedDeleteField": "This option allows you to delete any field from your embed.",
        "embedDeleteSubtitle": "This option allows you to delete any subtitle from your embed.",
        "embedList": "This option lists all your saved presets.",
        "embedRequireImageTitle": "How to use command options that require images",
        "embedRequireImage": "After the command option, specify an image. It can be an user mention (to use their avatar), an image URL, an attached image, {guildOption}, {userselfOption} (to use your avatar) or {ougiOption}.",
        "embedAttachedImageTitle": "How to use attached images",
        "embedAttachedImage": "If you attach any images to your message when executing this command, you can use them with any command option that requires images, just add {fileOption} and optionally, if you attach more than one image, the index (position of attachment, default is first).",
        "embedHelpDescription": "Use this command to create your very own custom embed. Just include one or more options with their respective content, after {commandName}.",
        "embedHelpDisclaimer": "Keep in mind, you may include at least one of these options and there is no specific order for them.",
        "embedExtraHelp": "You may also execute `ougi help embed` adding the name of any command option to preview detailed information about it.",
        "embedOptionsList": "List of command options for Ougi's embed command",
        "emojiHelpDesc": "Use this command to make Ougi send an emoji based on the provided emoji name. You can ask for more than one! You may also include {commandOption} as emoji name to chose a random emoji from the list.",
        "lookEmoji": "Take a look at the emoji list!",
        "pleasePage": "Uh, please provide a page number.",
        "notPage": "That's not a page yet.",
        "emojiListFooter": "spookyEmoji List by Ougi [{hwmnemoji} emoji in {numpage} pages]",
        "emojiListHelpDesc": "Take a look at all emoji that Ougi has access to. You can also browse by page.",
        "languageHelpDesc": "Change the language Ougi uses when talking to you.",
        "guildLanguageHelpDesc": "Change the language Ougi uses inside a specific Discord server.",
        "possibleLangInput": "You may specify a language name or its ISO code.",
        "sameAs": "It's the same as executing",
        "speakHelpDesc": "This command makes Ougi join your voice channel and say the prompted phrase. By default, Ougi will use the language set for the Discord server through {c} command.",
        "speakSpecificLang": "You may as well include double colons (::) and a language ISO code.",
        "curlHelpDesc": "Use this command to get detailed information about an user, a role, an emoji, a channel or even a Discord server.",
        "surveyHelpDesc": "Are you interested on sharing your thoughts on Ougi? Execute this command and Ougi will check if there's any new survey you haven't been notified about already.",
        "featuredCOVID19modules": "Featured COVID-19 commands",
        "availableCommandsListCOVID19": "Ougi got the following commands regarding COVID-19 pandemic:",
        "newsHelpDesc": "Fetch recent news about whatever you'd like in your preferred language.",
        "healthcareDesc": "Get a random healthcare advice to stay safe during the COVID-19 pandemic, in your preferred language.",
        "medicalDefinitionDesc": "Get definitions about a set of COVID-19 related concepts, in your preferred language.",
        "remindLang": "Set your preferred language using {c1}. Preview detailed commands usage using {c2}.",
        "readFullNews": "Click here to read the full article at {n}.",
        "adviceTitle": "Healthcare advice",
        "WHOCOVID19ADVICE": "Learn more at the World Health Organization site.",
        "hca1": "Keep your distance. It's recommended to maintain at least 1 meter distance from others whenever it's possible.",
        "hca2": "Wear a mask, specially if you cannot guarantee enough physical distance.",
        "hca3": "Cover a sneeze or cough with a tissue or bent elbow.",
        "hca4": "Immediately dispose of used tissue in a closed-lid bin.",
        "hca5": "Avoid touching eyes, nose and mouth.",
        "hca6": "Wash your hands frequently with soap and water, or with a hand sanitizer.",
        "hca7": "Stay at home if you are feeling unwell.",
        "hca8": "Always check local regulations before attending an event.",
        "hca9": "Always check local guidelines before planning any sort of event.",
        "hca10": "Brief others about precautions to prevent the spread of COVID-19 and ensure they are followed.",
        "hca11": "Choose outdoor venues over indoor spaces – if indoors, ensure the area is well-ventilated.",
        "hca12": "If you organize an event, minimize crowding by staggering arrivals and departures, numbering entries, designating seats/places and marking the floor to ensure physical distancing between people of at least one meter.",
        "hca13": "Provide others all necessary supplies – hand hygiene stations, hand sanitizer or soap and water, tissues, closed-lid bins, distance markers and masks if they need them.",
        "hca14": "Cancelling a planned event is an option that should always be considered, especially in case of non-essential events or when precautions cannot be implemented or adequately communicated.",
        "hca15": "Clean your hands before you put your mask on, as well as before and after you take it off, and after you touch it at any time.",
        "hca16": "Make sure your mask covers both your nose, mouth and chin.",
        "hca17": "When you take off a mask, store it in a clean plastic bag, and every day either wash it if it’s a fabric mask, or dispose of a medical mask in a trash bin.",
        "hca18": "Don’t use masks with valves.",
        "hca19": "Outbreaks have been reported in restaurants, choir practices, fitness classes, nightclubs, offices and places of worship where people have gathered, often in crowded indoor settings where they talk loudly, shout, breathe heavily or sing.",
        "hca20": "The risks of getting COVID-19 are higher in crowded and inadequately ventilated spaces where infected people spend long periods of time together in close proximity.",
        "hca21": "Crowded environments are where the virus appears to spread by respiratory droplets or aerosols more efficiently, so taking precautions is even more important.",
        "hca22": "Open a window. Increase the amount of natural ventilation when indoors.",
        "hca23": "Hands touch many surfaces and can pick up viruses. Once contaminated, hands can transfer the virus to your eyes, nose or mouth. From there, the virus can enter your body and infect you.",
        "hca24": "Clean and disinfect surfaces frequently especially those which are regularly touched, such as door handles, faucets and phone screens.",
        "hca25": "The most common symptoms of COVID-19 are fever, dry cough, and tiredness.",
        "hca26": "Other symptoms of COVID-19 that are less common and may affect some patients include loss of taste or smell, aches and pains, headache, sore throat, nasal congestion, red eyes, diarrhoea, or a skin rash.",
        "hca27": "Stay home and self-isolate even if you have minor symptoms such as cough, headache, mild fever, until you recover.",
        "hca28": "Call your health care provider or hotline for advice.",
        "hca29": "If you're feeling unwell and need to leave your house or have someone near you, wear a medical mask to avoid infecting others.",
        "hca30": "Keep up to date on the latest information from trusted sources, such as WHO or your local and national health authorities.",
        "mdThis": "Medical definition of {m}",
        "covid-19": "COVID-19",
        "coronavirus": "coronavirus",
        "face mask": "face mask",
        "pandemic": "pandemic",
        "quarantine": "quarantine",
        "safe distance": "safe distance",
        "symptoms": "symptoms",
        "md1": "COVID-19 is the disease caused by a new coronavirus called SARS-CoV-2. WHO first learned of this new virus on 31 December 2019, following a report of a cluster of cases of ‘viral pneumonia’ in Wuhan, People’s Republic of China.",
        "md2": "Coronaviruses are a type of virus. There are many different kinds, and some cause disease. A newly identified coronavirus, SARS-CoV-2, has caused a worldwide pandemic of respiratory illness, called COVID-19.",
        "md3": "A pandemic is defined as “an epidemic occurring worldwide, or over a very wide area, crossing international boundaries and usually affecting a large number of people”. The classical definition includes nothing about population immunity, virology or disease severity.",
        "md4": "A protective mask covering the nose and mouth or nose and eyes. It's currently being used to protect oneself and others from COVID-19.",
        "md5": "A state, period, or place of isolation in which people or animals that have arrived from elsewhere or been exposed to infectious or contagious disease (such as COVID-19) are placed.",
        "md6": "The World Health Organization recommends to stay at least 1 meter apart of other people, in order to minimize COVID-19 spread risks.",
        "md7": "The most common symptoms of COVID-19 are fever, dry cough, and tiredness. Other symptoms of COVID-19 that are less common and may affect some patients include loss of taste or smell, aches and pains, headache, sore throat, nasal congestion, red eyes, diarrhoea, or a skin rash.",
        "covidStatsTitle": "COVID-19 statistics",
        "covidStatsDesc": "Fetch COVID-19 statistics for a specific country by specifying a country name or a 2 characters country ISO code.",
        "covidStatsConfirmed": "Confirmed COVID-19 cases",
        "covidStatsCritical": "Critical COVID-19 cases",
        "covidStatsDeaths": "Confirmed COVID-19 deaths",
        "covidStatsRecovered": "Recovered from COVID-19 cases",
        "notCountry": "Invalid country name or ISO code.",
        "imageHelpDesc": "Use this command to get a random image from Internet based on the keywords you provide.",
        "snipeHelpDesc": "Use this command to make Ougi show any recently deleted messages in this channel. You may browse the deleted messages by specifying a number (starting in 1 for the last deletion).",
        "editsnipeHelpDesc": "Use this command to make Ougi show the original content of any recently edited messages in this channel. You may browse the edited messages by specifying a number (starting in 1 for the last edit).",
        "diceTitle": "Dice resulted in a {num}!",
        "diceHelpDesc": "Use this command to get a random number from Ougi's virtual dice.",
        "insufficientPerms": "Ougi lacks one or more permissions in this channel to work properly. If you are an administrator, make sure to give Ougi the following permissions and try again.",
        "CREATE_INSTANT_INVITE": "Create instant invite",
        "KICK_MEMBERS": "Kick members",
        "BAN_MEMBERS": "Ban members",
        "ADMINISTRATOR": "Administrator",
        "MANAGE_CHANNELS": "Manage channel",
        "MANAGE_GUILD": "Manage guild",
        "ADD_REACTIONS": "Add reactions",
        "VIEW_AUDIT_LOG": "View audit log",
        "PRIORITY_SPEAKER": "Priority speaker",
        "STREAM": "Stream",
        "VIEW_CHANNEL": "View channel",
        "SEND_MESSAGES": "Send messages",
        "SEND_TTS_MESSAGES": "Send TTS messages",
        "MANAGE_MESSAGES": "Manage messages",
        "EMBED_LINKS": "Embed links",
        "ATTACH_FILES": "Attach files",
        "READ_MESSAGE_HISTORY": "Read message history",
        "MENTION_EVERYONE": "Mention everyone",
        "USE_EXTERNAL_EMOJIS": "Use external emojis",
        "VIEW_GUILD_INSIGHTS": "View guild insights",
        "CONNECT": "Connect to voice channel",
        "SPEAK": "Speak in voice channel",
        "MUTE_MEMBERS": "Mute members",
        "DEAFEN_MEMBERS": "Deafen members",
        "MOVE_MEMBERS": "Move members",
        "USE_VAD": "Use voice activity",
        "CHANGE_NICKNAME": "Change nickname",
        "MANAGE_NICKNAMES": "Manage nicknames",
        "MANAGE_ROLES": "Manage roles",
        "MANAGE_WEBHOOKS": "Manage webhooks",
        "MANAGE_EMOJIS_AND_STICKERS": "Manage emojis and stickers",
        "USE_SLASH_COMMANDS": "Use slash commands",
        "REQUEST_TO_SPEAK": "Request to speak",
        "MANAGE_THREADS": "Manage threads",
        "USE_PUBLIC_THREADS": "Use public threads",
        "USE_PRIVATE_THREADS": "Use private threads",
        "USE_EXTERNAL_STICKERS": "Use external stickers",
        "resultsZero": "There aren't any results.",
        "calories": "Total calories: {num}",
        "tags": "Tags",
        "ingredients": "Ingredients",
        "recipeHelpDesc": "Use this command to get a recipe for (hopefully) any food.",
        "undeclaredString": "Oooh. Spooky phrase goes here!!! Seems like some lazy developer forgot to localize it.",
        "noNews": "No recent news found."
    },
    "es": {
        "helpTitle": "Página de ayuda con Ougi",
        "helpDesc": "He aquí algo de lo que vuestro amigo Ougi puede hacer.",
        "helpPrefix": "El glorosio prefijo de Ougi",
        "helpPrefixExplanation": "Si a Ougi queréis invocar, este prefijo habéis de usar...",
        "helpHelpCommand": "El comando de asistencia de Ougi",
        "helpHelpExplanation": "Muestra este magnífico menú de asistencia. También tenéis la posibilidad de usarlo para conseguir información desmenusada de los demás comandos.",
        "example": "Ejemplo",
        "output": "Resulta en",
        "availableCommands": "Mirad el pedazo de comandos que se trae Ougi",
        "availableCommandsList": "Por lo pronto, Ougi cuenta con estos comandos",
        "improving": "¡Echaremos caña para que algún día haya más!",
        "calories": "Calorías totales: {num}"
    },
    "mx": {
        "helpTitle": "Ayuda de Ougi",
        "helpDesc": "¿Qué puede hacer Ougi?",
        "helpPrefix": "El prefijo de Ougi",
        "helpPrefixExplanation": "Debes empezar el mensaje con este prefijo si quieres que Ougi ejecute cualquiera de sus comandos.",
        "helpHelpCommand": "Comando de ayuda",
        "helpHelpExplanation": "Este comando muestra este menú de ayuda. Es posible usarlo para obtener información detallada del resto de comandos.",
        "example": "Ejemplo",
        "output": "Resultado",
        "availableCommands": "Comandos disponibles",
        "availableCommandsList": "Por ahora, Ougi tiene los siguientes comandos",
        "improving": "¡Aún trabajando por mejorar!"
    }
}