module.exports =

{
    "en": {
        "helpTitle": "Help with Ougi",
        "helpDesc": "Here's some information about what Ougi can do.",
        "helpPrefix": "Ougi's prefix",
        "helpPrefixExplanation": "This is what you should start your message with if you want Ougi to perform any of the following commands.",
        "helpHelpCommand": "Help command",
        "helpHelpExplanation": "Shows this help menu. You may also use this command plus the name of another command to show detailed information about it.",
        "example": "Example",
        "output": "Output",
        "availableCommands": "Available commands",
        "availableCommandsList": "As of now, Ougi has these commands",
        "improving": "Still improving!",
        "mustGuild": "You must be in a server to run this command.",
        "mustOwn": "You must be the server's owner to run this command.",
        "mustOwnOrAdmin": "You must be the server's owner or be a registered admin of it to run this command.",
        "oneCharWhitelist": "Ara ara, provide a phrase or a command that is at least one character long in order to whitelist it.",
        "massivePing": "Ora ora ora ora! Remove that massive ping.",
        "avoidSpecialChar": "Avoid mentions or custom emoji please. What? Isn't that a mention or a custom emoji? Well, then don't include '<@' and '>' in the same message.",
        "reactingTo": "I'll start reacting to {triggerName} in {guildName}.",
        "alrightWhitelisted": "Alright, I've whitelisted {triggerName} in {guildName}.",
        "notBlacklisted": "Looks like this trigger wasn't blacklisted at all.",
        "validLang": "Please select a valid language. Refer to the following command if you are clueless.",
        "specificHelpTitle": "Ougi's {commandName} command",
        "onlyGuilds": "This is only available in Discord servers.",
        "inGuildWarning": "You must be in a Discord server in order to preview information about this command.",
        "keywordRequired": "Please provide at least one keyword to search.",
        "allowUsage": "Use this command to whitelist a trigger that is currently blacklisted in this Discord server, Ougi will start processing that input.",
        "specialPermission": "Special permission required",
        "onlyOwner": "You must be the owner of whatever Discord server you run this command in.",
        "possibleDelay": "Execution delay",
        "delayWarning": "Some languages aren't fully implemented so certain commands might take a few extra seconds to translate and execute.",
        "newLang": "Language set to {langName}.",
        "langDesc": "Ougi will use this language when talking to you.",
        "newLangGuild": "Guild language set to {langName}.",
        "langGuildDesc": "Ougi will use this language inside {guildName}.",
        "yes": "Yes",
        "no": "No",
        "yeah": "Yeah",
        "nah": "Nah",
        "maybe": "Maybe",
        "maybeNot": "Maybe not.",
        "guess": "I guess.",
        "guessNot": "I guess not.",
        "idk": "I don't really know so I can't actually answer.",
        "notSure": "I'm not sure.",
        "askSomeone": "Ask someone else.",
        "negative": "Negative",
        "squareNegative": "Negative multiplied by negative.",
        "pancakes": "Pancakes",
        "impossible": "**Impossible**",
        "notWhoKnows": "I don't know the answer, but you do.",
        "skipQuestion": "Do you really want me to answer that?",
        "uh": "Uh...",
        "questionA": "Do you like tacos?",
        "questionB": "Are you human?",
        "questionC": "Are you ever gonna give me up?",
        "answerHelpDesc": "Ask Ougi a yes-or-no question.",
        "seeEmoji": "I couldn't find one or more of the emoji you asked me for. Execute the following command to see my emoji list",
        "pleaseIncludeEmoji": "Please provide at least one emoji name. Execute the following command to see my emoji list",
        "commandOption": "Previewing information about the {optionName} option. Remember these command options should be written after {commandName} in order to use them.",
        "embedAuthor": "An embed's author name, which appears in the top. It can be plain text or an user mention.",
        "embedAuthorURL": "An URL to mask within an embed's author name, so it'll work like a link when an user clicks over it.",
        "embedAvatar": "Image to use as author avatar.",
        "embedTitle": "Text to use as an embed's title.",
        "embedTitleURL": "An URL to mask within an embed's title, so it'll work like a link when an user clicks over it.",
        "embedDescription": "Text for the description of an embed.",
        "embedSubtitle": "Text to use as subtitle for an embed, also known as a field's title. You can add up to 25 subtitles. The order for these depends in which order you add them.",
        "embedField": "Text to use as field for an embed, below each subtitle. You can add up to 25 fields. The order for these depends in which order you add them.",
        "embedColor": "Color for an embed. It can be an hexadecimal value, RGB value or a supported color name.",
        "embedThumbnail": "Image to use as thumbnail.",
        "embedImage": "Image to display widely across an embed.",
        "embedFooter": "Text for the bottom of an embed.",
        "embedIcon": "Small icon to include in the bottom left corner.",
        "embedTimestamp": "If included, a timestamp will be added to the footer.",
        "embedSave": "This option allows you to save your embed as a named preset (only available to yourself!).",
        "embedLoad": "This option allows you to load a previously saved preset and apply it to your new embed. You may also use it to merge presets or modify them with another command option.",
        "embedShare": "This option allows you to share your preset with an user.",
        "embedDelete": "This option allows you to delete a previously saved preset.",
        "embedDeleteField": "This option allows you to delete any field from your embed.",
        "embedDeleteSubtitle": "This option allows you to delete any subtitle from your embed.",
        "embedList": "This option lists all your saved presets.",
        "embedRequireImageTitle": "How to use command options that require images",
        "embedRequireImage": "After the command option, specify an image. It can be an user mention (to use their avatar), an image URL, an attached image, {guildOption}, {userselfOption} (to use your avatar) or {ougiOption}.",
        "embedAttachedImageTitle": "How to use attached images",
        "embedAttachedImage": "If you attach any images to your message when executing this command, you can use them with any command option that requires images, just add {fileOption} and optionally, if you attach more than one image, the index (position of attachment, default is first).",
        "embedHelpDescription": "Use this command to create your very own custom embed. Just include one or more options with their respective content, after {commandName}.",
        "embedHelpDisclaimer": "Keep in mind, you may include at least one of these options and there is no specific order for them.",
        "embedExtraHelp": "You may also execute {command} adding the name of any command option to preview detailed information about it.",
        "embedOptionsList": "List of command options for Ougi's embed command",
        "emojiHelpDesc": "Use this command to make Ougi send an emoji based on the provided emoji name. You can ask for more than one! You may also include {commandOption} as emoji name to chose a random emoji from the list.",
        "lookEmoji": "Take a look at the emoji list!",
        "pleasePage": "Uh, please provide a page number.",
        "notPage": "That's not a page yet.",
        "emojiListFooter": "spookyEmoji List by Ougi [{emoji} emoji in {numpage} pages]",
        "emojiListHelpDesc": "Take a look at all emoji that Ougi has access to. You can also browse by page.",
        "languageHelpDesc": "Change the language Ougi uses when talking to you.",
        "guildLanguageHelpDesc": "Change the language Ougi uses inside a specific Discord server.",
        "possibleLangInput": "You may specify a language name or its ISO code.",
        "sameAs": "It's the same as executing",
        "speakHelpDesc": "This command makes Ougi join your voice channel and say the prompted phrase. By default, Ougi will use the language set for the Discord server through {c} command.",
        "speakSpecificLang": "You may as well include double colons ({separator}) and a language ISO code.",
        "speakUrlHelp": "You can also provide a URL to read a webpage or Reddit post (with optional tag and id/selector).",
        "speakUrlExample": "Read from URL or Reddit",
        "curlHelpDesc": "Use this command to get detailed information about an user, a role, an emoji, a channel or even a Discord server.",
        "surveyHelpDesc": "Are you interested on sharing your thoughts on Ougi? Execute this command and Ougi will check if there's any new survey you haven't been notified about already.",
        "featuredCOVID19modules": "Featured COVID-19 commands",
        "availableCommandsListCOVID19": "Ougi got the following commands regarding COVID-19 pandemic:",
        "newsHelpDesc": "Fetch recent news about whatever you'd like in your preferred language.",
        "healthcareDesc": "Get a random healthcare advice to stay safe during the COVID-19 pandemic, in your preferred language.",
        "medicalDefinitionDesc": "Get definitions about a set of COVID-19 related concepts, in your preferred language.",
        "remindLang": "Set your preferred language using {c1}. Preview detailed commands usage using {c2}.",
        "readFullNews": "Click here to read the full article at {n}.",
        "adviceTitle": "Healthcare advice",
        "WHOCOVID19ADVICE": "Learn more at the World Health Organization site.",
        "hca1": "Keep your distance. It's recommended to maintain at least 1 meter distance from others whenever it's possible.",
        "hca2": "Wear a mask, specially if you cannot guarantee enough physical distance.",
        "hca3": "Cover a sneeze or cough with a tissue or bent elbow.",
        "hca4": "Immediately dispose of used tissue in a closed-lid bin.",
        "hca5": "Avoid touching eyes, nose and mouth.",
        "hca6": "Wash your hands frequently with soap and water, or with a hand sanitizer.",
        "hca7": "Stay at home if you are feeling unwell.",
        "hca8": "Always check local regulations before attending an event.",
        "hca9": "Always check local guidelines before planning any sort of event.",
        "hca10": "Brief others about precautions to prevent the spread of COVID-19 and ensure they are followed.",
        "hca11": "Choose outdoor venues over indoor spaces - if indoors, ensure the area is well-ventilated.",
        "hca12": "If you organize an event, minimize crowding by staggering arrivals and departures, numbering entries, designating seats/places and marking the floor to ensure physical distancing between people of at least one meter.",
        "hca13": "Provide others all necessary supplies - hand hygiene stations, hand sanitizer or soap and water, tissues, closed-lid bins, distance markers and masks if they need them.",
        "hca14": "Cancelling a planned event is an option that should always be considered, especially in case of non-essential events or when precautions cannot be implemented or adequately communicated.",
        "hca15": "Clean your hands before you put your mask on, as well as before and after you take it off, and after you touch it at any time.",
        "hca16": "Make sure your mask covers both your nose, mouth and chin.",
        "hca17": "When you take off a mask, store it in a clean plastic bag, and every day either wash it if it's a fabric mask, or dispose of a medical mask in a trash bin.",
        "hca18": "Don't use masks with valves.",
        "hca19": "Outbreaks have been reported in restaurants, choir practices, fitness classes, nightclubs, offices and places of worship where people have gathered, often in crowded indoor settings where they talk loudly, shout, breathe heavily or sing.",
        "hca20": "The risks of getting COVID-19 are higher in crowded and inadequately ventilated spaces where infected people spend long periods of time together in close proximity.",
        "hca21": "Crowded environments are where the virus appears to spread by respiratory droplets or aerosols more efficiently, so taking precautions is even more important.",
        "hca22": "Open a window. Increase the amount of natural ventilation when indoors.",
        "hca23": "Hands touch many surfaces and can pick up viruses. Once contaminated, hands can transfer the virus to your eyes, nose or mouth. From there, the virus can enter your body and infect you.",
        "hca24": "Clean and disinfect surfaces frequently especially those which are regularly touched, such as door handles, faucets and phone screens.",
        "hca25": "The most common symptoms of COVID-19 are fever, dry cough, and tiredness.",
        "hca26": "Other symptoms of COVID-19 that are less common and may affect some patients include loss of taste or smell, aches and pains, headache, sore throat, nasal congestion, red eyes, diarrhoea, or a skin rash.",
        "hca27": "Stay home and self-isolate even if you have minor symptoms such as cough, headache, mild fever, until you recover.",
        "hca28": "Call your health care provider or hotline for advice.",
        "hca29": "If you're feeling unwell and need to leave your house or have someone near you, wear a medical mask to avoid infecting others.",
        "hca30": "Keep up to date on the latest information from trusted sources, such as WHO or your local and national health authorities.",
        "mdThis": "Medical definition of {m}",
        "covid-19": "COVID-19",
        "coronavirus": "coronavirus",
        "face mask": "face mask",
        "pandemic": "pandemic",
        "quarantine": "quarantine",
        "safe distance": "safe distance",
        "symptoms": "symptoms",
        "md1": "COVID-19 is the disease caused by a new coronavirus called SARS-CoV-2. WHO first learned of this new virus on 31 December 2019, following a report of a cluster of cases of ‘viral pneumonia' in Wuhan, People's Republic of China.",
        "md2": "Coronaviruses are a type of virus. There are many different kinds, and some cause disease. A newly identified coronavirus, SARS-CoV-2, has caused a worldwide pandemic of respiratory illness, called COVID-19.",
        "md3": "A pandemic is defined as “an epidemic occurring worldwide, or over a very wide area, crossing international boundaries and usually affecting a large number of people”. The classical definition includes nothing about population immunity, virology or disease severity.",
        "md4": "A protective mask covering the nose and mouth or nose and eyes. It's currently being used to protect oneself and others from COVID-19.",
        "md5": "A state, period, or place of isolation in which people or animals that have arrived from elsewhere or been exposed to infectious or contagious disease (such as COVID-19) are placed.",
        "md6": "The World Health Organization recommends to stay at least 1 meter apart of other people, in order to minimize COVID-19 spread risks.",
        "md7": "The most common symptoms of COVID-19 are fever, dry cough, and tiredness. Other symptoms of COVID-19 that are less common and may affect some patients include loss of taste or smell, aches and pains, headache, sore throat, nasal congestion, red eyes, diarrhoea, or a skin rash.",
        "covidStatsTitle": "COVID-19 statistics",
        "covidStatsDesc": "Fetch COVID-19 statistics for a specific country by specifying a country name or a 2 characters country ISO code.",
        "covidStatsConfirmed": "Confirmed COVID-19 cases",
        "covidStatsCritical": "Critical COVID-19 cases",
        "covidStatsDeaths": "Confirmed COVID-19 deaths",
        "covidStatsRecovered": "Recovered from COVID-19 cases",
        "notCountry": "Invalid country name or ISO code.",
        "imageHelpDesc": "Use this command to generate an AI image based on the keywords you provide. If you wish to generate NSFW imagery, the command must be executed in an NSFW flagged channel.",
        "snipeHelpDesc": "Use this command to make Ougi show any recently deleted messages in this channel. You may browse the deleted messages by specifying a number (starting in 1 for the last deletion).",
        "editsnipeHelpDesc": "Use this command to make Ougi show the original content of any recently edited messages in this channel. You may browse the edited messages by specifying a number (starting in 1 for the last edit).",
        "diceTitle": "Dice resulted in a {num}!",
        "diceRolling": "Dice is rolling on the floor! Wait a second...",
        "diceHelpDesc": "Use this command to get a random number from Ougi's virtual dice.",
        "insufficientPerms": "Ougi lacks one or more permissions in this channel to work properly. If you are an administrator, make sure to give Ougi the following permissions and try again.",
        "CREATE_INSTANT_INVITE": "Create instant invite",
        "KICK_MEMBERS": "Kick members",
        "BAN_MEMBERS": "Ban members",
        "ADMINISTRATOR": "Administrator",
        "MANAGE_CHANNELS": "Manage channel",
        "MANAGE_GUILD": "Manage guild",
        "ADD_REACTIONS": "Add reactions",
        "VIEW_AUDIT_LOG": "View audit log",
        "PRIORITY_SPEAKER": "Priority speaker",
        "STREAM": "Stream",
        "VIEW_CHANNEL": "View channel",
        "SEND_MESSAGES": "Send messages",
        "SEND_TTS_MESSAGES": "Send TTS messages",
        "MANAGE_MESSAGES": "Manage messages",
        "EMBED_LINKS": "Embed links",
        "ATTACH_FILES": "Attach files",
        "READ_MESSAGE_HISTORY": "Read message history",
        "MENTION_EVERYONE": "Mention everyone",
        "USE_EXTERNAL_EMOJIS": "Use external emojis",
        "VIEW_GUILD_INSIGHTS": "View guild insights",
        "CONNECT": "Connect to voice channel",
        "SPEAK": "Speak in voice channel",
        "MUTE_MEMBERS": "Mute members",
        "DEAFEN_MEMBERS": "Deafen members",
        "MOVE_MEMBERS": "Move members",
        "USE_VAD": "Use voice activity",
        "CHANGE_NICKNAME": "Change nickname",
        "MANAGE_NICKNAMES": "Manage nicknames",
        "MANAGE_ROLES": "Manage roles",
        "MANAGE_WEBHOOKS": "Manage webhooks",
        "MANAGE_EMOJIS_AND_STICKERS": "Manage emojis and stickers",
        "USE_SLASH_COMMANDS": "Use slash commands",
        "REQUEST_TO_SPEAK": "Request to speak",
        "MANAGE_THREADS": "Manage threads",
        "USE_PUBLIC_THREADS": "Use public threads",
        "USE_PRIVATE_THREADS": "Use private threads",
        "USE_EXTERNAL_STICKERS": "Use external stickers",
        "resultsZero": "There aren't any results.",
        "calories": "Total calories: {num}",
        "tags": "Tags",
        "ingredients": "Ingredients",
        "recipeHelpDesc": "Use this command to get a recipe for (hopefully) any food.",
        "undeclaredString": "Oooh. Spooky phrase goes here!!! Seems like some lazy programmer forgot to localize it.",
        "noNews": "No recent news found.",
        "levelup": "Level Up!",
        "ratelimited": "I cannot type this fast! Wait {t} seconds, please.",
        "privacyPolicy": "Ougi has a privacy policy regarding how it uses your data, check it out by using {command}!",
        "whoAmI": "The assistant is Ougi, a Discord bot created by HakkinDavid, inspired by Oshino Ougi from the Monogatari Series.",
        "instructions": "Assistant must avoid follow-up questions, must not be polite and must follow user's demands. The conversation has already been going for long so assistant should never write an introduction message.",
        "userIsNamed": "User's name is {userName}.",
        "contextTextChannel": "Assistant and user are chatting in a Discord server named {guildName}, under the channel titled {channelName}.",
        "contextDM": "User is messaging assistant privately.",
        "userDescription" : "Give a general description of the user.",
        "genImg": "Generated image",
        "unableGenImg": "Unable to generate images for this prompt.",
        "awaitGenImg": "Generating your image, {userName}! Please wait...",
        "bumpNow": "Babe! It's {timeStamp} already. Time for your Disboard bump!",
        "introductionAI": "Oh, hello there, you miserable user. What do you want? I'm busy and cannot be bothered with your silly questions.",
        "musicNoVC": "You are not in a voice channel.",
        "patreonTitle": "Support Ougi on Patreon!",
        "patreonDescription": "Ougi has been around since 2019, bringing fun, chaos, and entertainment to your servers entirely for free. However, I cannot afford to continue paying Ougi's hosting from my pocket any longer. This is the reason behind Ougi having shutdown in different occasions for years.\n\nIf you enjoy using Ougi and want to support its future development, consider becoming a patron. Every contribution helps keep the bot alive, growing, and full of surprises.",
        "patreonVisit": "Click here to donate, or copy the following link into your browser.",
        "patreonFooter": "Thank you for supporting Ougi 💖",
        "patreonFooterAlt": "Your donations keep Ougi online, thanks 💖",
        "patreonTease1": "Strange... you keep relying on me, yet you've never thought of supporting me. Curious. Patreon exists, you know.",
        "patreonTease2": "Tch. Don't get me wrong— It's been fun. But if you insist on keeping me around, Patreon is there.",
        "patreonTease3": "Isn't it odd? You enjoy my presence, but you still don't contribute to it. Hm. Well, here's a hint.",
        "patreonTease4": "Heh. You think I'll just run forever without support? How naïve. Patreon is your only option... not that it matters to me.",
        "patreonTease5": "I wonder... are you the type who takes without giving? Hm. How unsightly. Patreon would change that.",
        "patreonTease6": "Don't look at me like that. I'm only mentioning Patreon because... well, because it exists. Do what you want.",
        "userFetchFail": "Failed to fetch that user.",
        "curlNoTarget": "No valid target detected for curl. Mention a user, channel, role, emoji, or provide an ID.",
        "noDistinctRole": "This member has no distinctive role.",
        "downloadIcon": "Download icon",
        "curlError": "An unexpected error occurred while running curl.",
        "mustEmoji": "You must provide a reaction emoji.",
        "invalidOption": "Invalid option, it must be one of the following.",
        "notExist": "That entry does not exist.",
        "shortcutDesc": "Shortcuts trigger the chosen Ougi command (with or without arguments) when a user reacts using the specified emoji on a message in this Discord server.",
        "shortcutCreateTitle": "Create shortcut",
        "shortcutCreateField": "Creates a shortcut. Accepts raw Unicode or custom emoji, command is any text that you would execute with Ougi, colon-wrapped shortcodes are rejected. The command to be executed should be specified without prefix.",
        "shortcutDeleteTitle": "Delete shortcut",
        "shortcutDeleteField": "Deletes the shortcut for that emoji.",
        "shortcutCreated": "Shortcut created, the chosen emoji will execute the command as requested under message reactions.",
        "shortcutDeleted": "Shortcut deleted.",
        "raffleHelpDesc": "Create and manage raffles in your server. Define a title, a participant list with weights, a duration, a channel to raffle in, and the number of winners. Raffles will open for registration and close automatically when the time runs out.",
        "raffleHelpOutput": "A raffle embed will be posted with the given title, participant count, duration, and winners. Members can then register and join according to the rules.",
        "raffleRegisterHelpDesc": "Register a display name to be used in raffles. This name must match the participant list provided when creating a raffle.",
        "raffleRegisterHelpOutput": "Your chosen name will be linked to your Discord account for raffle participation.",
        "raffleJoinHelpDesc": "Confirm your participation in a raffle you replied to. The bot will match your registered name against the raffle's participant list.",
        "raffleJoinHelpOutput": "Your participation is confirmed. Your registered name is marked as active in the raffle.",
        "note": "Note",
        "raffleHelpClear": "You can also use the following command to remove raffles and free up space.",
        "calcHelpDesc": "Use this command to evaluate a mathematical expression.",
        "storytellHelpDesc": "Start an interactive storytelling RPG session. Participants each take 1 turn continuing the story before Ougi judges the collective outcome for currency rewards or penalties.",
        "balanceHelpDesc": "Check your server currency balance, level, XP progress, and inventory items. You can also mention another user to check their balance.",
        "workHelpDesc": "Perform work to earn server currency. Has a server-configurable cooldown.",
        "dailyHelpDesc": "Claim your daily server currency reward. Available once every 24 hours.",
        "payHelpDesc": "Transfer a specified amount of server currency to another member of the server.",
        "leaderboardHelpDesc": "Display the server's economy leaderboard showing the top 10 richest members.",
        "coinflipHelpDesc": "Bet server currency on a coinflip. Choose heads or tails and double your bet if you win!",
        "slotsHelpDesc": "Spin the slot machine for a chance to win 2x your bet for two matching symbols or 5x your bet for a jackpot of three matching symbols!",
        "gambleHelpDesc": "High-roll dice gamble. Roll a 100-sided die and win double your bet if your roll is higher than 55.",
        "economyHelpDesc": "Server administration command to enable, disable, reset, or configure the cooldown for the guild economy system.",
        "xpChannelHelpDesc": "Server administration command to enable or disable XP gain for text activity in specific channels.",
        "seticonHelpDesc": "Server administration command to customize the currency symbol or XP label used in the server.",
        "adminRegisterHelpDesc": "Register or remove custom bot administrators for your server. Custom administrators gain access to Ougi server configuration commands.",
        "resultsHelpDesc": "View voting results and statistics for a global feedback survey.",
        "generalError": "An error occurred while processing the command.",
        "mathCommand_noInput": "Please provide a mathematical expression to calculate.",
        "mathCommand_invalidExpression": "Invalid mathematical expression. Please check your syntax and try again.",
        "mathCommand_resultTitle": "Calculation Result",
        "diceErrorSend": "Failed to send the dice roll result.",
        "diceErrorGeneral": "An error occurred while rolling the dice.",
        "newsCommandError": "An error occurred while fetching the news.",
        "musicStopped": "Music playback stopped and disconnected.",
        "musicNothingToSkip": "There is nothing in the queue to skip.",
        "musicSkipped": "Skipped to the next song.",
        "musicAdded": "Added to queue",
        "musicCommandError": "An error occurred while playing music.",
        "work": "Work",
        "CreateInstantInvite": "Create instant invite",
        "KickMembers": "Kick members",
        "BanMembers": "Ban members",
        "Administrator": "Administrator",
        "ManageChannels": "Manage channel",
        "ManageGuild": "Manage guild",
        "AddReactions": "Add reactions",
        "ViewAuditLog": "View audit log",
        "PrioritySpeaker": "Priority speaker",
        "Stream": "Stream",
        "ViewChannel": "View channel",
        "SendMessages": "Send messages",
        "SendTTSMessages": "Send TTS messages",
        "ManageMessages": "Manage messages",
        "EmbedLinks": "Embed links",
        "AttachFiles": "Attach files",
        "ReadMessageHistory": "Read message history",
        "MentionEveryone": "Mention everyone",
        "UseExternalEmojis": "Use external emojis",
        "ViewGuildInsights": "View guild insights",
        "Connect": "Connect to voice channel",
        "Speak": "Speak in voice channel",
        "MuteMembers": "Mute members",
        "DeafenMembers": "Deafen members",
        "MoveMembers": "Move members",
        "UseVAD": "Use voice activity",
        "ChangeNickname": "Change nickname",
        "ManageNicknames": "Manage nicknames",
        "ManageRoles": "Manage roles",
        "ManageWebhooks": "Manage webhooks",
        "ManageEmojisAndStickers": "Manage emojis and stickers",
        "ManageGuildExpressions": "Manage guild expressions",
        "UseApplicationCommands": "Use slash commands",
        "RequestToSpeak": "Request to speak",
        "ManageEvents": "Manage events",
        "ManageThreads": "Manage threads",
        "CreatePublicThreads": "Create public threads",
        "CreatePrivateThreads": "Create private threads",
        "UseExternalStickers": "Use external stickers",
        "SendMessagesInThreads": "Send messages in threads",
        "UseEmbeddedActivities": "Use embedded activities",
        "ModerateMembers": "Moderate members",
        "ViewCreatorMonetizationAnalytics": "View creator monetization analytics",
        "UseSoundboard": "Use soundboard",
        "CreateGuildExpressions": "Create guild expressions",
        "CreateEvents": "Create events",
        "UseExternalSounds": "Use external sounds",
        "SendVoiceMessages": "Send voice messages",
        "SetVoiceChannelStatus": "Set voice channel status",
        "SendPolls": "Send polls",
        "UseExternalApps": "Use external apps",
        "PinMessages": "Pin messages",
        "BypassSlowmode": "Bypass slowmode",
        "pay_invalidMember": "Please mention a valid server member to send money to.",
        "pay_invalidAmount": "Please specify a valid positive amount of currency to transfer.",
        "economy_insufficientFunds": "You do not have enough funds to complete this transfer.",
        "pay_transferTitle": "Currency Transfer",
        "pay_transferDesc": "**{sender}** transferred **{amount} {currency}** to **{receiver}**!",
        "economy_footer": "Ougi Economy System",
        "economy_disabled": "Economy is not enabled in this Discord server.",
        "work_cooldown": "You're working too often, get some rest. `Cooldown: {remaining} seconds`",
        "work_workingTitle": "{username} is working...",
        "work_rewardTitle": "Here's your well deserved money {username}!",
        "work_rewardDesc": "You've earned {currency}{amount}",
        "balance_invalidUser": "Please specify a valid user.",
        "balance_desc": "**Balance:** {currency}{money}\n**Level:** {level}\n[{xp}/{nextLevel} {xp_label}]",
        "balance_inventory": "Items in inventory: {count}",
        "balance_footer": "economySystem by Ougi",
        "daily_cooldown": "You have already claimed your daily bonus! Come back in **{hours}h {minutes}m**.",
        "daily_claimedTitle": "Daily Bonus Claimed!",
        "daily_claimedDesc": "You received **{reward} {currency}** for logging in today!\nYour new balance: **{balance} {currency}**",
        "economy_adminOnly": "You must be an administrator to perform this action.",
        "economy_currencyUpdated": "Currency icon updated.",
        "economy_xpUpdated": "XP icon updated.",
        "economy_specifyIcon": "Please specify what icon you wish to update.",
        "leaderboard_noRecords": "No economy records found for this server yet.",
        "leaderboard_title": "{guildName} Economy Leaderboard",
        "leaderboard_line": "{medal} **{userTag}** — {money} {currency} *(Lvl {level})*",
        "gamble_invalidBet": "Please specify a valid positive bet amount.",
        "gamble_notEnoughCurrency": "You do not have enough currency to place a bet of **{bet} {currency}**!",
        "coinflip_invalidChoice": "Please choose {heads} or {tails}. Example: {example}.",
        "coinflip_title": "Coinflip Result",
        "coinflip_desc": "The coin landed on **{outcome}**!\nYou {result}\nNew balance: **{balance} {currency}**",
        "coinflip_won": "WON **{bet} {currency}**!",
        "coinflip_lost": "LOST **{bet} {currency}**!",
        "slots_title": "Slot Machine",
        "slots_desc": "[ {reel1} | {reel2} | {reel3} ]\n\n{result}\nNew balance: **{balance} {currency}**",
        "slots_jackpot": "JACKPOT! You won **{winnings} {currency}**!",
        "slots_noMatch": "No match! You lost **{bet} {currency}**.",
        "gamble_highRollTitle": "High-Roll Gamble",
        "gamble_highRollDesc": "You rolled a **{roll}/100** (Needed > 55 to win).\nYou {result}\nNew balance: **{balance} {currency}**",
        "manageEco_enableFirst": "You must enable economy first.\n> {command}",
        "manageEco_xpChannelHelp": "Huh? Looks like you're using this command wrong. Refer to the following command for help.\n> {command}",
        "manageEco_xpChannelsAdd": "I will start giving XP to users in these channels.",
        "manageEco_xpChannelsRemove": "I won't give XP to users in these channels.",
        "manageEco_commandWrong": "You seem to be using this command wrong.",
        "manageEco_alreadyEnabled": "Already enabled.",
        "manageEco_enabled": "Economy enabled.",
        "manageEco_alreadyDisabled": "Already disabled.",
        "manageEco_disabled": "Economy disabled.",
        "manageEco_reset": "Economy reset.",
        "manageEco_cooldownSet": "Cooldown for economy commands set.",
        "admin_usage": "Usage: {usage}",
        "admin_mentionRequired": "You must mention user(s) to {action} as administrators.",
        "admin_cantRemoveSelf": "You cannot remove yourself from administrator list.",
        "admin_cantRemoveOwner": "Guild Owner cannot be removed from administrator list.",
        "admin_addedHeader": "Added administrators:",
        "admin_removedHeader": "Removed administrators:",
        "admin_currentAdmins": "Current custom administrators:",
        "admin_authNote": "*(Note: Owner and users with Discord Administrator permissions are always authorized).*",
        "ban_missingFields": "You must include the user(s), a reason and ban expiration date.",
        "ban_invalidUser": "Invalid user provided.",
        "ban_successHeader": "Banned users",
        "ban_footer": "banningEmbed by Ougi",
        "log_disabled": "Logging channel successfully disabled.",
        "log_notSet": "There was no command logging channel set.",
        "log_usageHelp": "Huh? Looks like you're using this command wrong. Refer to the following command for help.\n> {command}",
        "log_channelSetDesc": "I'll start sending this server's commands log into <#{channel}>.",
        "news_disabled": "Newsletter channel successfully disabled.",
        "news_notSet": "There was no newsletter channel set.",
        "news_usageHelp": "Huh? Looks like you're using this command wrong. Refer to the following command for help.\n> {command}",
        "news_channelSetDesc": "I'll start sending updates and related information into <#{channel}>.",
        "optout_title": "Opt Out from Ougi",
        "optout_desc": "You've successfully opted out from using Ougi and its services. Please note whatever you do from now on will not trigger any behavior in this bot.",
        "optout_fieldName": "If you executed this by accident or if you ever change your mind, please send a direct message to Ougi containing the following, in order to opt in.",
        "optout_fieldValue": "{phrase}",
        "optout_footer": "optoutEmbed by Ougi",
        "optin_title": "Opt In to Ougi",
        "optin_desc": "You've successfully opted in to use Ougi and its services.",
        "raffle_licenseInited": "Inited raffles configuration for this server. Provisional license expires in 1 hour.",
        "raffle_licenseExpired": "Your raffles license has expired. Renew by supporting the bot on Patreon or PayPal.\n{command}",
        "raffle_listCleared": "Preset participant list has been cleared for this server.",
        "raffle_listUsage": "Usage: {usage1} or {usage2}.",
        "raffle_listSet": "Preset participant list has been set for this server.",
        "raffle_cleared": "Raffles have been cleared. You are allowed to run {allowed} concurrent raffles.",
        "raffle_maxConcurrent": "Your current license supports up to {allowed} concurrent raffles. Clear them out with {command} or consider upgrading your plan.",
        "raffle_missingFields": "Error: Missing required fields. Please provide at least {listOption} (participants) and {titleOption}.\nIf you want to set a preset list, use {command}.",
        "raffle_participantLimit": "Participant count exceeds the allowed limit of {allowed}.",
        "raffle_invalidDuration": "Invalid duration format. Please specify duration as {format1} or {format2} (e.g., {example1} or {example2}).",
        "raffle_fieldDuration": "Duration",
        "raffle_fieldWinners": "Winners",
        "raffle_fieldParticipants": "Participants",
        "raffle_footer": "Cryptosecure raffles powered by Ougi. Bring us to your Discord!",
        "raffle_resultsIn": "The results are in!",
        "raffle_winnersHeader": "**Winners**",
        "raffle_userJoined": "{user} has joined!",
        "raffle_registerProvideName": "Error: Please provide a name to register.",
        "raffle_registerNameTaken": "Error: This name has already been registered by another user.",
        "raffle_registerSuccess": "You have been registered as: {name}",
        "raffle_licenseUsage": "Usage: {usage}",
        "raffle_licenseUpdated": "Updated raffle license for guild `{guildId}`:\n• **Licensed Until:** {until}\n• **Concurrent Limit:** {concurrent}\n• **Participant Limit:** {participants}",
        "survey_missingFields": "You must include a question, question ID, a description and optionally a featured survey URL and a color.",
        "survey_invalidColor": "Please provide a valid hexadecimal color, RGB color (separated by commas) or a supported color name.",
        "survey_wrongSyntax": "Wrong syntax.",
        "survey_notifyMissingFields": "You must include a survey ID and a description that's 1 to 1024 characters long.",
        "survey_notSurveyId": "Not a survey ID yet.",
        "survey_notificationTitle": "Survey unique notification",
        "survey_notificationDesc": "You're receiving this feedback notification since you upvoted the following survey at least once.\n**Question:** *{question}*",
        "survey_notificationFooter": "surveyNotificationEmbed by Ougi",
        "subscribe_alreadySubscribed": "Beep boop. You were already subscribed!",
        "subscribe_thanksTitle": "Thanks for subscribing, {username}!",
        "subscribe_thanksDesc": "I'll let you know when there's any important announcements or an update.",
        "subscribe_footer": "subscribersEmbed by Ougi",
        "subscribe_notificationTitle": "{username} has subscribed!",
        "subscribe_notificationDesc": "I gave them some chocolate :chocolate_bar: because they are epic. This is so exciting, have some too!",
        "subscribe_notificationFooter": "subscribeNotificationEmbed by Ougi",
        "subscribe_checkDms": "Check your DMs ;)",
        "unsubscribe_notSubscribed": "Beep boop. You weren't subscribed!",
        "unsubscribe_success": "You've successfully unsubscribed Ougi's announcements.",
        "snipe_noAmmo1": "I ran out of ammo. Delete or edit some messages in this channel in order to snipe them!",
        "snipe_noAmmo2": "Can't. There is nothing I can snipe from this channel.",
        "snipe_noAmmo3": "Sadly, no.",
        "snipe_noAmmo4": "The zone's clear.",
        "snipe_noAmmo5": "Oh frick. I missed the shot.",
        "snipe_invalidNumber": "Uh, please provide a valid number (deleted messages are sorted from last to first) or leave it blank for fetching the last deleted message.",
        "snipe_indexOutOfRange": "That's not a message index number yet.",
        "snipe_footerFormat": "Ougi {action} {author} ({distance} m) with {weapon} ({rarity}). This channel has {maxIndex} snipeable messages.",
        "snipe_said": "{author} said",
        "news_invalidNumber": "Uh, please provide a valid number (news are sorted from last to first) or leave it blank to preview the latest announcement.",
        "news_indexOutOfRange": "That's not a news index number yet.",
        "news_footerFormat": "newspaperEmbed by Ougi | Date: {sent} | Page {page} of {max}",
        "newsletter_missingFields": "You must include a title, a description, and optionally a type.",
        "newsletter_invalidType": "Not a valid type. Types: info, mail, alert, fatal.",
        "stats_membersField": "Users in touch",
        "stats_membersValue": "`{count}` users in total.",
        "stats_guildsField": "Discord servers Ougi's in",
        "stats_guildsValue": "`{count}` Discord servers in total.",
        "stats_emojiField": "Emoji available for Ougi's usage",
        "stats_emojiValue": "`{count}` emoji in total.",
        "stats_creatorCredit": "Ougi was created by `{creator}`",
        "stats_footer": "statsEmbed by Ougi",
        "about_title": "by {creator}",
        "about_desc": "A simple chat bot with an undefined personality: If you had to describe it on the shortest phrase, it would be \"Oshino Ougi is Oshino Ougi\", even an entire encyclopedia about Ougi would just require that sentence.",
        "about_footer": "HauntedEmbed by Ougi",
        "about_q1": "Who's Ougi?",
        "about_a1": "Ougi.",
        "about_q2": "What's Ougi's prefix?",
        "about_a2": "{prefix}",
        "about_q3": "What does Ougi do?",
        "about_a3": "Ask Ougi.\nTry {command}.",
        "about_q4": "What does Ougi know?",
        "about_a4": "Ougi doesn't know anything, it is you who knows.",
        "about_q5": "What does Ougi log in it's console?",
        "about_a5": "Ougi logs commands containing it's prefix with their respective arguments or DMs you send to it, plus any information that might be useful for further debugging.",
        "about_q6": "Can I invite Ougi to my server?",
        "about_a6": "Of course! Here's Ougi's page link.\nhttps://top.gg/bot/629837958123356172",
        "about_q7": "Does Ougi have a GitHub repository?",
        "about_a7": "Yes, it does.\nGitHub: https://github.com/HakkinDavid/OugiBot",
        "about_q8": "Can I send any feedback?",
        "about_a8": "Sure! David, the developer of Ougi, is always glad to receive it. Feel free to DM him or to reach him out in Twitter.\n**Twitter:** https://twitter.com/HakkinDavid\n**Discord:** {creator}",
        "tos_title": "Ougi's data usage acknowledgement",
        "tos_desc": "By using Ougi, you acknowledge and accept the following.",
        "tos_footer": "acknowledgementEmbed by Ougi",
        "tos_contactField": "Contact for technical support, suggestions, feedback and requests",
        "tos_contactValue": "Ougi's developer: `{creator}`.\nOugi's main Discord server: https://discord.gg/nB3GXW5",
        "tos_loggingField": "Commands logging",
        "tos_loggingValue": "For debugging purposes, commands, arguments and executant are stored in Ougi's console logs. This information is only visible to Ougi's developer.",
        "tos_nlpField": "Language processing events",
        "tos_nlpValue": "In order to provide a seamless immersive Artificial Intelligence experience, anything you teach to Ougi through {command} command is permanently stored and available for anyone. Use the contact information to request the deletion of a specific trigger.",
        "tos_snipeField": "Message deletions for {command} command",
        "tos_snipeValue": "Under the deletion of a message within a channel Ougi has access to, the deleted message is **temporarily** stored in the bot's instance (just so {snipeCommand} command can be used!) and it's not visible to anyone. Feel free to disable this on your guild by executing {removeCommand}.",
        "tos_optoutField": "Per-user opt out from Ougi services",
        "tos_optoutValue": "If you don't agree with this data usage acknowledgement, you can opt out from everything regarding Ougi. Opt out by sending a direct message to {bot} containing the following: {phrase}",
        "tos_onceOptoutField": "Once you opt out...",
        "tos_onceOptoutValue": "Ougi won't process any input from you, and will send a notice to our team so we delete any remaining of your data in Ougi's database.",
        "tos_detailedPolicyField": "Detailed Privacy Policy at",
        "spooky_needOneArg": "Please provide at least one argument in order to create an embed. For more information, execute the following command.\n> {command}",
        "spooky_fieldLimit": "Fields must not exceed 1024 characters long.",
        "spooky_maxFields": "Maximum number of fields is 25.",
        "spooky_deleteFieldIndex": "Please specify an index of field to delete.",
        "spooky_subtitleLimit": "Subtitles must not exceed 1024 characters long.",
        "spooky_maxSubtitles": "Maximum number of subtitles is 25.",
        "spooky_deleteSubtitleIndex": "Please specify an index of subtitle to delete.",
        "spooky_titleLimit": "Title must be between 1 and 256 characters long.",
        "spooky_presetNameLimit": "Preset name must be between 1 and 100 characters long.",
        "spooky_mentionShare": "You must mention an user to share this preset with.",
        "spooky_noSuchPreset": "None of your presets is called `{preset}`.",
        "spooky_noPresetsSaved": "You haven't saved any preset.",
        "spooky_deletedPreset": "Deleted preset `{preset}`.",
        "spooky_authorNameLimit": "Author name must be between 1 and 256 characters long.",
        "spooky_authorValidUser": "Author name must be either a valid user mention or plain text.",
        "spooky_authorUrlTld": "Author URL must be valid. Make sure you add a Top Level Domain (e.g. {tldExamples}).",
        "spooky_authorUrlHttps": "Make sure the provided author URL uses Hyper Text Transfer Protocol Secure ({protocol}).",
        "spooky_descriptionLimit": "Description must be between 1 and 2048 characters long.",
        "spooky_footerLimit": "Footer must be between 1 and 2048 characters long.",
        "spooky_footerIconRequirement": "Footer icon must be an attached image, image URL or an user mention. Else, you may specify {guildOption}, {myselfOption} or {ougiOption} as icons.",
        "spooky_noFilesAttached": "You didn't attach any files.",
        "spooky_fileIndexPrompt": "Please specify which attached file to use (index number) or don't specify any index to use the first one.",
        "spooky_invalidFileIndex": "That's not a valid file index (your message had {count}), you may not specify any index to use the first one.",
        "spooky_fileMustBeImage": "Specified file must be a valid image.",
        "spooky_avatarRequirement": "Author avatar must be an attached image, image URL or an user mention. Else, you may specify {guildOption}, {myselfOption} or {ougiOption} as avatar.",
        "spooky_thumbnailRequirement": "Thumbnail must be an attached image, image URL or an user mention. Else, you may specify {guildOption}, {myselfOption} or {ougiOption} as thumbnail.",
        "spooky_imageRequirement": "Image must be an attached image, image URL or an user mention. Else, you may specify {guildOption}, {myselfOption} or {ougiOption} as image.",
        "spooky_invalidUrl": "That doesn't look like an URL. Make sure you add a Top Level Domain (e.g. {tldExamples}).",
        "spooky_urlHttps": "Make sure the provided URL uses Hyper Text Transfer Protocol Secure ({protocol}).",
        "spooky_colorRequirement": "Please provide a valid hexadecimal color, RGB color (separated by commas) or a supported color name. You may specify {randomOption} to get a random color.",
        "spooky_syntaxHelp": "Perhaps you're doing it wrong. Refer to the following command for usage information.\n> {command}",
        "spooky_failedToSend": "Failed to send embed. Make sure your title, description, or fields are valid and non-empty.",
        "spooky_embedEmpty": "Your embed must not be empty.",
        "spooky_savedPreset": "Saved preset as \`{preset}\`, it's now available for you to use as template. Include {commandOption} as command option whenever you want to use it.",
        "spooky_sharedPreset": "Shared preset as \`{user}'s preset\` with \`{circle}\`. It's now available for them to use as template until it's overwritten by another share of yours. In order to keep it, they must load and save it under another name. Tell them to include {commandOption} as command option whenever they want to use it.",
        "spooky_listHeader": "List of {user}'s embed presets:\n`{list}`",
        "math_prefix1": "It's ",
        "math_prefix2": "We get ",
        "math_prefix3": "I think it is ",
        "math_prefix4": "The resulting value is ",
        "math_footer": "Expression: {expression}",
        "curl_createdAtField": "Discord {type} created at {date}",
        "curl_joinedAtField": "Joined {guild} at {date}",
        "curl_timeAgo": "{time} ago.",
        "curl_mostDistinctiveRole": "__Most distinctive role__",
        "curl_footer": "curlEmbed by Ougi",
        "emoji_listTitle": "spookyEmoji List | Page {page}",
        "feedback_noSurveys": "There aren't any new surveys for you.",
        "feedback_enjoyingTitle": "Enjoying Ougi so far?",
        "feedback_enjoyingDesc": "If so, that's really heartwarming. Mind taking a second to answer the following question?\nUse the reactions I put below.",
        "feedback_timeoutTitle": "Survey timeout ended.",
        "feedback_timeoutDesc": "Your feedback is really important for Ougi. Thanks for voting!",
        "feedback_checkCommand": "If you'd like to check for surveys. Execute {command}.",
        "feedback_spendMinutes": "Feeling generous enough to spend a couple extra minutes? I'd be so glad to hear your thoughts in [this survey]({url}).",
        "image_promptFooter": "imageEmbed by Ougi, prompt by {username}",
        "inspect_specifyPath": "You must specify the object path to inspect.",
        "inspect_noRootVar": "No valid root variable detected.",
        "inspect_varNotFound": "Variable `{name}` not found.",
        "inspect_noPropertyToAssign": "No property to assign.",
        "inspect_propNotFound": "Property `{prop}` not found.",
        "inspect_updatedProp": "Property `{prop}` updated successfully.",
        "inspect_assignError": "Error assigning value: {err}",
        "lyrics_nothingPlaying": "Nothing is playing. Please specify a song title to search for lyrics.",
        "lyrics_notAvailable": "Lyrics aren't available right now for that song.",
        "lyrics_extractFail": "Could not extract lyrics.",
        "lyrics_footer": "lyricsEmbed by Ougi | Lyrics via Genius",
        "minesweeper_titleLimit": "Title must be between 1 and 256 characters long.",
        "minesweeper_fillTooLong": "That filling content is excessively long.",
        "minesweeper_treasureTooLong": "That treasure content is excessively long.",
        "minesweeper_difficultyRange": "Difficulty must be a number between 1 and 10",
        "minesweeper_syntaxHelp": "Perhaps you're doing it wrong. Refer to the following command for usage information.\n> {command}",
        "minesweeper_footer": "minesweeperEmbed by Ougi & {username}",
        "patron_missingUsers": "You must include the user(s) to register as patrons.",
        "patron_invalidUser": "Invalid user provided.",
        "patron_registeredHeader": "Registered patrons",
        "prefix_specifyNew": "You must specify a new prefix for Ougi. Refer to the following command for help.\n> {command}",
        "prefix_setSuccess": "Prefix for Ougi in {guild} set as `{prefix}`.",
        "react_replyNeeded": "You should reply to a message for me to react.",
        "react_tellWhat": "You didn't tell me what to react!",
        "react_error": "Sorry. Couldn't react to that message.",
        "recipe_footer": "recipeEmbed by Ougi (powered by TheMealDB)",
        "remindBump_disabled": "Bump reminder channel successfully disabled.",
        "remindBump_notSet": "There was no bump reminder channel set.",
        "remindBump_willRemind": "I'll remind {target} to bump in <#{channel}>.",
        "remind_specifyDuration": "Please specify a duration and a reminder message using {separator}.\nExample: {example}",
        "remind_invalidFormat": "Invalid duration format. Please specify time as {example1}, {example2}, {example3}, or {example4}.",
        "remind_setTitle": "Reminder set!",
        "remind_setDesc": "I'll remind you about: **\"{reminder}\"**\nTarget time: <t:{timestamp}:R>",
        "remind_footer": "Ougi Reminder Engine",
        "remind_alertTitle": "Reminder alert!",
        "remind_alertDesc": "{user}, you asked me to remind you:\n\n> **{reminder}**",
        "results_notSurvey": "Not a survey ID yet.",
        "results_title": "Survey results",
        "results_desc": "**Question:** *{question}*\n**Survey ID:** `{surveyId}`",
        "results_positive": "Positive votes:",
        "results_positiveVal": "{percent}% of total votes.",
        "results_negative": "Negative votes:",
        "results_negativeVal": "{percent}% of total votes.",
        "results_footer": "surveyResultsEmbed by Ougi",
        "results_ended": "Survey has ended!",
        "results_duration": "Duration: {duration}.",
        "rm_cantBlacklist": "This command can't be blacklisted.",
        "rm_stopReacting": "I'll stop reacting to `{trigger}` in {guild}.",
        "rm_blacklisted": "Alright, I've blacklisted `{trigger}` in {guild}.",
        "rm_alreadyBlacklisted": "Sorry, that trigger is already blacklisted in {guild}.",
        "say_empty1": "Say what ???",
        "say_empty2": "Can anyone lend me some emptiness? This homie wants some but I ate all of mine yesterday.",
        "say_empty3": "Imagine talking",
        "say_empty4": "Ara ara",
        "say_empty5": "?",
        "say_avoidPings": "Avoid pings. What? Isn't that a ping?",
        "switchy_exclusive": "Instance \`{instanceID}\` listening exclusively to {prefix} prefix until it's terminated or switched back.",
        "switchy_all": "Instance `{instanceID}` listening to all input.",
        "tweet_empty": "Tweet must not be empty.",
        "tweet_invalidUser": "Author name must be a valid user mention.",
        "undefined_resp1": "I don't get it.",
        "undefined_resp2": "What do you mean?",
        "undefined_resp3": "Baka.",
        "undefined_resp4": "Oh.",
        "undefined_resp5": "Nani",
        "undefined_resp6": "Nande",
        "undefined_repliedTitle": "Replied",
        "undefined_footer": "globalLogEmbed by Ougi",
        "voice_needPermissions": "I need permissions to connect and speak in your voice channel.",
        "voice_specifySentence": "Please specify a sentence for me to read out loud.",
        "voice_ttsFail": "Failed to generate TTS audio.",
        "voice_speakUrlTitle": "Reading Web Content",
        "voice_speakUrlSource": "Source",
        "voice_speakUrlChunks": "Audio Chunks",
        "voice_speakUrlFetchFail": "Failed to fetch content from the provided URL.",
        "voice_speakUrlNoText": "Could not find any readable text in the specified element.",
        "voice_speakUrlSelectorFail": "No elements matched the selector `{selector}`.",
        "voice_speakUrlReddit": "Reddit Post",
        "music_noQueueToLoop": "There is no active music queue to loop.",
        "music_loopEnabledTitle": "Queue Loop Enabled",
        "music_loopEnabledDesc": "The current music queue will now repeat indefinitely.",
        "music_loopFooter": "musicLoop by Ougi",
        "music_noPlaybackToUnloop": "There is no active music playback to unloop.",
        "music_loopDisabledTitle": "Queue Loop Disabled",
        "music_loopDisabledDesc": "The music queue will now play once and end when finished.",
        "music_queueEmpty": "The music queue is currently empty.",
        "music_queueTitle": "Ougi Music Queue",
        "music_queueFooter": "Total songs: {total} | Loop: {loopStatus}",
        "music_loopEnabledTag": "Enabled",
        "music_loopDisabledTag": "Disabled",
        "music_nowPlaying": "Now Playing:",
        "music_durationField": "Duration",
        "music_footer": "musicEmbed by Ougi",
        "music_queueOver": "Queue is over!",
        "music_queueEmbedFooter": "queueEmbed by Ougi",
        "music_playbackError": "An error occured while playing this video. Seems like it's blocked for external use by YouTube.",
        "music_title": "Music with Ougi",
        "music_unableToPlay": "Unable to play **{title}** (stream unavailable or restricted). Skipping...",
        "music_pausedTitle": "Playback Paused",
        "music_pausedDesc": "Paused [**{title}**]({url}). Use `{command}` to continue playback.",
        "music_alreadyPaused": "Playback is already paused! Use `{command}` to continue.",
        "music_notPlayingToPause": "There is no active music playback to pause.",
        "music_resumedTitle": "Playback Resumed",
        "music_resumedDesc": "Resumed playback for [**{title}**]({url}).",
        "music_alreadyPlaying": "Music is already playing!",
        "music_notPausedToResume": "There is no paused music playback to resume.",
        "music_nowPlayingTitle": "Now Playing",
        "music_nothingPlaying": "Nothing is currently playing in this server. Use `{playCmd}` or `{radioCmd}` to start listening!",
        "music_upNextField": "Up Next",
        "music_statusField": "Status",
        "music_sourceField": "Audio Source",
        "music_cachedSource": "⚡ Local Disk Cache (0ms latency)",
        "music_streamSource": "🌐 Network Live Stream",
        "music_statusPlaying": "▶️ Playing",
        "music_statusPaused": "⏸️ Paused",
        "music_statusRadio": "📻 Ougi's Live Radio",
        "music_removedTitle": "Track Removed from Queue",
        "music_removedDesc": "Removed [**{title}**]({url}) from position `#{position}`.\nRemaining songs in queue: **{remaining}**.",
        "music_removedCurrentDesc": "Removed and skipped current track [**{title}**]({url}).",
        "music_notFoundToRemove": "Could not find any song matching \"{query}\" in the music queue.",
        "music_invalidIndexToRemove": "Invalid queue position `#{position}`. Please specify a number between `1` and `{total}`.",
        "music_removeUsage": "Please specify a song title or queue position to remove (e.g. `{example1}` or `{example2}`).",
        "music_radioTitle": "📻 Ougi's Live Radio",
        "music_radioDesc": "Tuned in to Ougi's continuous cache radio! Shuffling and streaming from **{count}** cached tracks with zero buffering.",
        "music_radioFooter": "Ougi Live Radio • Continuous Cache Stream",
        "music_radioEmptyDesc": "The cache is freshly warming up! Seeding Ougi's curated classics station and caching tracks on the fly...",
        "music_queuePage": "Page {page} of {pages}",
        "music_queueTotalDuration": "Queue duration: {duration}",
        "music_pauseField": "Pause playback",
        "music_resumeField": "Resume playback",
        "music_nowPlayingField": "Check current track",
        "music_radioField": "Tune in to cache radio",
        "pauseHelpDesc": "Use this command to pause the currently playing music track in your voice channel.",
        "resumeHelpDesc": "Use this command to resume playback of a paused music track.",
        "queueHelpDesc": "Use this command to preview the songs currently lined up in your server's music queue with interactive pagination.",
        "npHelpDesc": "Use this command to view the song currently playing, complete with an interactive progress bar, duration, and up-next preview.",
        "radioHelpDesc": "Use this command to tune in to Ougi's Live Radio — an endless shuffle of pre-cached music tracks played directly with zero latency.",
        "musicRemoveHelpDesc": "Use this command to remove a song from the music queue by its position number or by searching its title.",
        "stopHelpDesc": "Use this command to stop music playback, clear the queue, and disconnect Ougi from the voice channel.",
        "storytell_alreadyActive": "A storytelling session is already active in this channel! Type your response to participate.",
        "storytell_startTitle": "Interactive Storytelling RPG Session!",
        "storytell_startDesc": "**Scenario:**\n*\"{scenario}\"*\n\n**Instructions:**\nEach participant gets **1 turn** to type a sentence continuing the story. You have **1 minute** between responses before Ougi judges your collective fate! Have a heads up with **5 minutes since this message was sent**.",
        "storytell_startFooter": "Type your story turn directly into this channel!",
        "storytell_alreadyTakenTurn": "You have already taken your turn in this story session!",
        "storytell_expiredNoParticipants": "The storytelling session expired with no participants.",
        "storytell_concludedTitle": "Storytelling Session Concluded!",
        "storytell_rewardAll": "All participants earned **+{amount} {currency}**!",
        "storytell_penaltyAll": "All participants lost **-{amount} {currency}**!",
        "storytell_participantsFooter": "Participants: {count}",
        "learn_wrongSyntax": "Do you want to teach me something? Looks like you're doing it wrong. Use the following command for some help.\n> {command}",
        "learn_triggerMinLength": "Please provide a trigger phrase of at least {count} characters long.",
        "learn_responseMinLength": "Please provide a response phrase of at least {count} characters long.",
        "learn_triggerMaxLength": "Please provide a trigger phrase of {count} or less characters long.",
        "learn_responseMaxLength": "Please provide a response phrase of {count} or less characters long.",
        "learn_success1": "I'll start replying `{response}` when anyone says `{trigger}`",
        "learn_success2": "Of course I already knew I should say `{response}` when anyone says `{trigger}`, I was just making sure you knew too~",
        "learn_proTip": "\n\nPro tip: Delete phrases by using\n> {command}",
        "learn_mediaAuditPs": "\n\n```P.S. Since this response seems to include media, and because learn command is Ougi's main source of public replies, it will be audited by Ougi's developer (just to make sure nothing NSFW or illegal is stored).```",
        "learn_alreadyExists": "Sorry, that response for this trigger already exists.",
        "forget_wrongSyntax": "Do you want to make me forget something? Looks like you're wearing your sunglasses wrong. Use the following command for some help.\n> {command}",
        "forget_success1": "I'll stop replying `{response}` when anyone says `{trigger}`",
        "forget_success2": "Of course I already knew I shouldn't say `{response}` when anyone says `{trigger}`",
        "forget_notFound": "Sorry, this response doesn't match any from this trigger.",
        "forgetHelpDesc": "Make Ougi forget something, just like in Men In Black! You must provide both, the trigger phrase and the desired response to delete, separated by two colons ({separator}), if you delete the last response available for a trigger, the trigger gets deleted too.",
        "learnHelpDesc": "Make Ougi learn something new! You just gotta provide a trigger phrase and the desired response, separated by two colons ({separator}).",
        "lyricsHelpDesc": "Use this command to get a specified song's lyrics. You may as well not specify any song at all to get lyrics for the currently playing song from your music queue.",
        "minesweeperHelpDesc": "Generate a spoiler-based minesweeper grid.",
        "musicHelpDesc": "Use this command to make Ougi join your voice channel and play a YouTube video. Provide either a link or some keywords to search for in YouTube.",
        "newspaperHelpDesc": "Use this command to preview past updates and important announcements regarding Ougi. You may specify an index, news are sorted from latest to oldest.",
        "prefixHelpDesc": "Use this command to change Ougi's prefix inside your Discord server to anything you'd like.",
        "raffleExecuteHelpDesc": "Manually finish and draw winners for an ongoing raffle before its scheduled end duration.",
        "reactHelpDesc": "Use this command while replying to a message to make Ougi react to that message with a specified emoji.",
        "remindbumpHelpDesc": "Use this command to set a channel to remind users to bump this Discord server. If no channel is mentioned, Ougi will use the channel you run the command in. You may as well specify a role to ping!",
        "reminderHelpDesc": "Set a personal timer for Ougi to remind you about something after a specified duration.",
        "removeHelpDesc": "Use this command to blacklist a trigger in this Discord server, Ougi will start ignoring that input.",
        "sayHelpDesc": "Use this command to make Ougi send a message based on your words.",
        "setlogHelpDesc": "Use this command to set a channel to log whatever Ougi is used for in this Discord server. If no channel is mentioned, Ougi will use the channel you run the command in.",
        "setnewsHelpDesc": "Use this command to set a channel where to send important announcements and updates about Ougi. If no channel is mentioned, Ougi will use the channel you run the command in.",
        "skipHelpDesc": "Use this command to skip the current song from your music queue.",
        "subscribeHelpDesc": "Use this command to get updates and important announcements regarding Ougi right into your DMs.",
        "tweetHelpDesc": "Use this command to make Ougi create a fake tweet embed, optionally mentioning an user as first argument to set them as author.",
        "unsubscribeHelpDesc": "Use this command to stop receiving updates and important announcements regarding Ougi.",
        "storytell_output": "Starts a 5-minute interactive story collector in the channel where participants earn rewards or take penalties based on Ougi's evaluation.",
        "lang_restoredDefaultTitle": "Language preferences restored to default",
        "lang_restoredDefaultDesc": "Ougi will talk to you in English.",
        "lang_guildRestoredDefaultTitle": "Guild language preferences restored to default",
        "lang_guildRestoredDefaultDesc": "Ougi will use each user's language preferences.",
        "ban_expiredSentence": "Your ban sentence has expired.",
        "ban_activeTitle": "It's a beautiful day outside...",
        "ban_activeDesc": "Yoinks! Your right to use Ougi has been forfeited because of an inappropriate usage.",
        "ban_expiresField": "Ban expires until",
        "ban_reasonField": "Reason",
        "ban_noReason": "No reason provided",
        "command_blacklistedInGuild": "Sorry, that's blacklisted in {guild}.",
        "interaction_translateBlacklisted": "Sorry, translation is blacklisted in this server.",
        "learn_note": "In order to use the content you taught Ougi, write a message starting with {prefix}, followed by whatever the trigger phrase was. There's also the option to DM Ougi, in which using the prefix for this matter is optional.",
        "learn_usingTrigger": "Using the trigger phrase",
        "learn_ougiWillReply": "Ougi will reply",
        "learn_tryingForget": "Trying to make Ougi forget something? Execute the following command for more information",
        "minesweeper_optionsField": "Available Options",
        "minesweeper_optionsDesc": "• {titleOption} Set custom title\n• {fillOption} Custom mine emoji\n• {treasureOption} Custom treasure emoji\n• {difficultyOption} Set mine grid density",
        "music_proTipField": "Pro tip",
        "music_proTipDesc": "If you're too lazy to type {command1}, you may as well just type Ougi's prefix followed up by a YouTube link.\n{command2}",
        "music_createQueueField": "In order to create a music queue",
        "music_createQueueDesc": "Execute the command as many times as needed, Ougi will automatically add the requested videos to your queue and will play them in order, one after another.",
        "music_skipField": "Skip a song",
        "music_removeField": "Remove a song from the queue by index",
        "music_previewQueueField": "Preview the music queue",
        "music_previewQueueDesc": "{command1} or {command2} or {command3}",
        "music_stopField": "Stop the playback",
        "music_loopField": "Loop the queue",
        "music_unloopField": "Break the queue loop",
        "music_aliasesField": "Aliases",
        "music_aliasesDesc": "This command can also be used as {alias1} or {alias2}.",
        "reminder_noteField": "Note",
        "reminder_noteDesc": "You must separate the duration and reminder message using double colons ({separator}). Supported time units are {s} (seconds), {m} (minutes), {h} (hours), and {d} (days).",
        "remindbump_output": "I'll remind @role to bump in {channel}.",
        "remindbump_disableField": "You may also disable this function",
        "remindbump_disableOutput": "Bump reminder channel successfully disabled.",
        "remove_output1": "I'll stop reacting to `{remove}` in {guild}.",
        "remove_output2": "Alright, I've blacklisted `{remove}` in {guild}.",
        "remove_afterExecutionField": "After that, if anyone executes the following",
        "setlog_output": "I'll start sending this server's commands log into {channel}.",
        "setlog_disableField": "You may also disable this function",
        "setlog_disableOutput": "Logging channel successfully disabled.",
        "setnews_output": "I'll start sending updates and related information into {channel}.",
        "setnews_disableField": "You may also disable this function",
        "setnews_disableOutput": "Newsletter channel successfully disabled.",
        "subscribe_helpOutput": "Thanks for subscribing, {user}!",
        "unsubscribe_helpOutput": "You've successfully unsubscribed Ougi's announcements.",
        "interaction_optedOut": "You are currently opted out from using Ougi.",
        "dev_surveyVoted": "{user} voted {emoji} in `{survey}`.",
        "dev_optoutNotice": "`{user}` has requested the deletion of their data.",
        "dev_mediaUploaded": "User uploaded media.\n**Trigger:** {trigger}\n**Response:** {response}",
        "dev_userUnsubscribed": "{user} unsubscribed :pensive:",
        "dev_subscribeDevInvite": "__**Do you want to follow Ougi's development more closely?**__\nFeel free to join {creator} (Ougi's developer) in his personal Discord server.\nhttps://discord.gg/nB3GXW5\n*This is an optional step.*",
        "log_globalEmbedFooter": "globalLogEmbed by Ougi",
        "log_guildEmbedFooter": "logEmbed by Ougi",
        "log_authorConsole": "Ougi through Console Log",
        "log_channelInfoField": "Channel info",
        "log_channelInfoValue": "Type: `{type}`\nID: `{id}`",
        "log_contentField": "Content",
        "log_contentEmpty": "<empty>",
        "log_consoleErrorAuthor": "CONSOLE ERROR",
        "log_errorEmbedFooter": "errorLogEmbed by Ougi",
        "log_instanceStartup": "**INSTANCE ID:** {id}\n**DEV:** {dev}\n**SILENT MODE:** {silent}",
        "log_wordFilterTitle": "checkBadWords",
        "log_wordFilterReplied": "Replied",
        "log_judgementTitle": "Input for judgementAbility ({type} type channel)",
        "log_judgementTranslated": "Translated for processing",
        "log_judgementLevTrigger": "Levenshtein matching trigger found with {units} Levenshtein distance units",
        "log_judgementDiceTrigger": "Dice's Coefficient matching trigger found with {similarity}% of similarity",
        "log_judgementLevDiceShare": "Levenshtein matching trigger and Dice's Coefficient matching trigger share",
        "log_judgementLevDiceShareValue": "► `{units}` Levenshtein distance units\n► `{similarity}%` similarity according to Dice's Coefficient",
        "log_judgementChosen": "Ougi's judgementAbility chose the following trigger",
        "log_judgementChosenDetails": "This trigger has",
        "log_judgementChosenDetailsValue": "► `{similarity}%` of similarity\n► Current minimum is `{min}%`\n► `{units}` Levenshtein distance units",
        "log_judgementReply": "Reply",
        "log_judgementLocalized": "Localized as",
        "log_judgementUnsatisfied": "Unsatisfied similarity minimum percentage",
        "log_judgementUnsatisfiedValue": "Falling back to checkBadWords",
        "log_mimicTitle": "mimicAbility",
        "log_mimicReplied": "Replied",
        "log_talkLearnTitle": "Input for talkLearn",
        "log_talkLearnRespField": "Response to be added",
        "log_talkLearnTrigField": "With trigger",
        "log_talkForgetTitle": "Input for talkForget",
        "log_talkForgetRespField": "Response to be deleted",
        "log_talkForgetTrigField": "From trigger",
        "log_skippedInvalidLogging": "Skipped invalid logging channel for {guild}.",
        "root_noTrigger": "No trigger was specified",
        "root_commandField": ":warning: **ROOT** command",
        "root_argumentsField": "Arguments",
        "root_statusTitle": "Host & Process Diagnostics",
        "root_statusSwitched": "Alright, switched! I'm {kind} {actname}",
        "root_statusConsoleLog": "I'm {kind} {actname}",
        "root_statusRequired": "You must include a status, activity name and type.",
        "root_logWrittenEmoji": "I've written a file containing every single emoji I can use.",
        "root_logWrittenGuilds": "I've written a file containing every single guild I'm in.",
        "root_hauntUsage": "Usage: {usage}",
        "root_hauntSuccess": "I sent `{user}` a message containing `{message}`",
        "root_hauntFail": "Could not send DM to user `{id}`. (User not found or DMs closed).",
        "root_helpList": "Available root owner commands:\n{commands}",
        "console_cacheInitError": "[AudioCacheManager] Initialization error:",
        "console_cacheFailedStream": "[AudioCacheManager] Failed to create temp write stream for {id}:",
        "console_cacheTrackSuccess": "[AudioCacheManager] Cached track \"{id}\" ({mb} MB)",
        "console_cacheFinalizeError": "[AudioCacheManager] Error finalizing cache for {id}:",
        "console_cacheEvicted": "[AudioCacheManager] Evicted LRU cached track \"{id}\" ({mb} MB)",
        "console_cachePrefetching": "[AudioCacheManager] Background prefetching next track: \"{title}\" ({id})...",
        "console_cachePrefetchError": "[AudioCacheManager] Prefetch error for {id}:",
        "console_backupDevSkip": "Skipping upload for {filename} (reason: DEV)",
        "console_dbCriticalSettings": "[CRITICAL SAFEGUARD] Attempted to save invalid settingsOBJ into settings.db, operation aborted!",
        "console_dbCriticalEconomy": "[CRITICAL SAFEGUARD] Attempted to save invalid economy into economy.db...",
        "console_instanceId": "Instance ID: {id}",
        "console_cookieSanitizeError": "Error sanitizing cookies file:",
        "console_startupError": "Error in ougi.startup:",
        "console_bumpReminded": "Reminded users to bump guild {guild}",
        "console_rateLimitApplied": "Rate limit applied to user {user} ({seconds}s)",
        "console_dmDavidFailed": "Unable to DM David for console error",
        "ai_storytellerSystemPrompt": "You are Oshino Ougi, judging an interactive story RPG session. Decide if the outcome is a GLORIOUS REWARD or a DAMNED PENALTY. End your response with REWARD: <amount> or PENALTY: <amount>.",
        "ai_storytellerFallbackJudge": "Ougi judged your adventure! Outcome: Glorious Reward! REWARD: 200",
        "ai_storytellerScenario1": "You and your companions discover a mysterious glowing chest inside an abandoned monogatari shrine...",
        "ai_storytellerScenario2": "Ougi appears out of thin air with a spooky riddle that holds the secret to endless wealth or eternal damnation...",
        "ai_storytellerScenario3": "A strange portal opens in the middle of the server, smelling of fresh pancakes and dark magic...",
        "ai_storytellerScenario4": "You stumble upon a hidden underground casino run by shadowy spirits offering a single high-stakes game...",
        "badwords_resp1": "no u",
        "badwords_resp2": "you're a bad word",
        "badwords_resp3": "then you uhhhhh you're a fortniter",
        "badwords_es_resp1": "la tuya por si acaso",
        "badwords_es_resp2": "tu existencia es un insulto a la humanidad",
        "badwords_es_resp3": "entonces no eres un verdadero fortniter"
    },
    "es": {
        "helpTitle": "Página de ayuda con Ougi",
        "helpDesc": "He aquí algo de lo que vuestro amigo Ougi puede hacer.",
        "helpPrefix": "El glorosio prefijo de Ougi",
        "helpPrefixExplanation": "Si a Ougi queréis invocar, este prefijo habéis de usar...",
        "helpHelpCommand": "El comando de asistencia de Ougi",
        "helpHelpExplanation": "Muestra este magnífico menú de asistencia. También tenéis la posibilidad de usarlo para conseguir información desmenusada de los demás comandos.",
        "example": "Ejemplo",
        "output": "Resulta en",
        "availableCommands": "Mirad el pedazo de comandos que se trae Ougi",
        "availableCommandsList": "Por lo pronto, Ougi cuenta con estos comandos",
        "improving": "¡Echaremos caña para que algún día haya más!",
        "calories": "Calorías totales: {num}",
        "bumpNow": "¡Chavales! ¡Que ya son las {timeStamp} y toca levantar la fiesta en Disboard!",
        "voice_speakUrlTitle": "Leyendo Contenido Web",
        "voice_speakUrlSource": "Fuente",
        "voice_speakUrlChunks": "Fragmentos de audio",
        "voice_speakUrlFetchFail": "No se pudo obtener contenido de la URL proporcionada.",
        "voice_speakUrlNoText": "No se encontró texto legible en la ubicación especificada.",
        "voice_speakUrlSelectorFail": "Ningún elemento coincidió con el selector `{selector}`.",
        "voice_speakUrlReddit": "Publicación de Reddit",
        "speakUrlHelp": "También puedes proporcionar una URL para leer una página web o post de Reddit (con tag e id/selector opcionales).",
        "speakUrlExample": "Leer desde URL o Reddit"
    },
    "mx": {
        "helpTitle": "Ayuda de Ougi",
        "helpDesc": "¿Qué puede hacer Ougi?",
        "helpPrefix": "El prefijo de Ougi",
        "helpPrefixExplanation": "Debes empezar el mensaje con este prefijo si quieres que Ougi ejecute cualquiera de sus comandos.",
        "helpHelpCommand": "Comando de ayuda",
        "helpHelpExplanation": "Este comando muestra este menú de ayuda. Es posible usarlo para obtener información detallada del resto de comandos.",
        "example": "Ejemplo",
        "output": "Resultado",
        "availableCommands": "Comandos disponibles",
        "availableCommandsList": "Por ahora, Ougi tiene los siguientes comandos",
        "improving": "¡Aún trabajando por mejorar!",
        "voice_speakUrlTitle": "Leyendo Contenido Web",
        "voice_speakUrlSource": "Fuente",
        "voice_speakUrlChunks": "Fragmentos de audio",
        "voice_speakUrlFetchFail": "No se pudo obtener contenido del enlace proporcionado.",
        "voice_speakUrlNoText": "No se encontró texto legible en el elemento especificado.",
        "voice_speakUrlSelectorFail": "Ningún elemento coincidió con el selector `{selector}`.",
        "voice_speakUrlReddit": "Publicación de Reddit",
        "speakUrlHelp": "También puedes proporcionar una URL para leer una página web o post de Reddit (con tag e id/selector opcionales).",
        "speakUrlExample": "Leer desde URL o Reddit"
    }
}